# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comboboxtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from amu_database import getBedListSize, getPatientsinBed, getPatientInfo

bedColumn = 0
idColumn = 1
nameColumn = 2
detailsColumn = 3
diagnosisColumn = 4
isoColumn = 5
dischargeColumn = 6
dis_loungeColumn = 7
dis_sumColumn = 8
dis_medColumn = 9
downstreamColumn = 10
deathColumn = 11

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(250, 160, 60, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cardio"))
        self.comboBox.setItemText(2, _translate("MainWindow", "endo"))
        self.comboBox.setItemText(3, _translate("MainWindow", "gastro"))
        self.comboBox.setItemText(4, _translate("MainWindow", "geriatrics"))
        self.comboBox.setItemText(5, _translate("MainWindow", "resp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())








    def displayList(self):      # this function updates the list of patients currently in an AMU bed that is saved in database
        # listnow = getPatientsinBed, getPatientsinLounge
        # table = bedTable, loungeTable

        size = getBedListSize()
        print(size)
        self.bedTable.setRowCount(size) #setting the table row size
        row = 0
        #listnow = getPatientinWaitlist() # get the waitlist in the database as a list
        listnow = getPatientsinBed()
        print(listnow)
        for pat in listnow: #looping through each row of waitlist and add it to the table {first, last, age, gender, diagnosis, time, isolate}
            
            patient = getPatientInfo(pat[0])
            print(patient)
            isoStatus = ""
            if patient[6] == 0:
                isoStatus = "N"
            elif patient[6] != 0:
                isoStatus = "Y"

            checkBox_discharge = QtWidgets.QTableWidgetItem()
            checkBox_discharge.setCheckState(0)

            checkBox_discharge = QtWidgets.QTableWidgetItem()
            checkBox_discharge.setCheckState(0)

            checkBox_dischargeLounge = QtWidgets.QTableWidgetItem()
            checkBox_dischargeLounge.setCheckState(0)

            checkBox_dischargeSum = QtWidgets.QTableWidgetItem()
            checkBox_dischargeSum.setCheckState(0)

            checkBox_dischargeMed = QtWidgets.QTableWidgetItem()
            checkBox_dischargeMed.setCheckState(0)

            self.bedTable.setRowHeight(row, 70)
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)

            self.bedTable.setItem(row, bedColumn, QtWidgets.QTableWidgetItem(pat[1])) # bed
            item.setText(str(patient[0]))
            self.bedTable.setItem(row, idColumn, item) #id
            self.bedTable.setItem(row, nameColumn, QtWidgets.QTableWidgetItem("{} {}".format(patient[1], patient[2]))) # name
            self.bedTable.setItem(row, detailsColumn, QtWidgets.QTableWidgetItem(("Age: {} \nGender: {}").format(patient[3],patient[4]))) #age and gender
            self.bedTable.setItem(row, diagnosisColumn, QtWidgets.QTableWidgetItem(("Diagnosis: {}").format(patient[5]))) # diagnosis
            self.bedTable.setItem(row, isoColumn, QtWidgets.QTableWidgetItem(isoStatus)) # isolation
            self.bedTable.setItem(row, dischargeColumn, checkBox_discharge) # discharge status
            self.bedTable.setItem(row, dis_loungeColumn, checkBox_dischargeLounge)
            self.bedTable.setItem(row, dis_sumColumn, checkBox_dischargeSum)
            self.bedTable.setItem(row, dis_medColumn, checkBox_dischargeMed)
            # zaty pls help ;-; # downstream ward
            self.bedTable.setItem(row, deathColumn, checkBox_death) # death

            row = row+1