# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dischargeList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from waitlist import Ui_waitlist
from amu_database import deletePat, getListSize, getContent, deletePat

class Ui_dischargeList(object):
    def returntoMain(self, win):
        from monitor import Ui_MainWindow2 # function is imported here to prevent runtime callback (circular import)
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()
        win.close()

    def deletePatient(self):
        currow= self.tableWidget.currentRow()
        first = self.tableWidget.item(currow, 0).text()
        last = self.tableWidget.item(currow, 1).text()
        # deletePat(first, last) 
        self.displayList()

    def displayList(self):
        pass

    def setupUi(self, dischargeList):
        dischargeList.setObjectName("dischargeList")
        dischargeList.resize(1440, 847)
        dischargeList.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        dischargeList.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(dischargeList)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.returntoMain(dischargeList))
        self.back.setGeometry(QtCore.QRect(70, 60, 131, 41))
        self.back.setObjectName("back")
        self.Delete = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.deletePatient())
        self.Delete.setGeometry(QtCore.QRect(1242, 61, 121, 41))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.Delete.setFont(font)
        self.Delete.setAutoDefault(True)
        self.Delete.setDefault(False)
        self.Delete.setFlat(False)
        self.Delete.setObjectName("Delete")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(75, 141, 1291, 631))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(520, 40, 361, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(35)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        # self.back = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.back(dischargeList))
        dischargeList.setCentralWidget(self.centralwidget)


        self.retranslateUi(dischargeList)
        QtCore.QMetaObject.connectSlotsByName(dischargeList)

    def retranslateUi(self, dischargeList):
        _translate = QtCore.QCoreApplication.translate
        dischargeList.setWindowTitle(_translate("dischargeList", "Discharge List"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dischargeList", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dischargeList", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dischargeList", "Location"))
        self.title.setText(_translate("dischargeList", "DISCHARGE LIST"))
        self.back.setText(_translate("dischargeList", "Return to Main"))
        self.Delete.setText(_translate("dischargeList", "Delete Patient"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dischargeList = QtWidgets.QMainWindow()
    ui = Ui_dischargeList()
    ui.setupUi(dischargeList)
    dischargeList.show()
    sys.exit(app.exec_())
