 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from amu_database import getBedListSize, getPatientsinBed, getPatientInfo, getLoungeListSize, getPatientsinLounge, getPatientsDownstream, getDownstreamListSize, getPatientsDischarged, deletePatfromBed, updateCheck_discharge, updateCheck_dischargeLounge, updateCheck_dischargeSum, updateCheck_dischargeMed, updateWard, updateCheck_death, getWardAvailability




class Ui_patientStatus(object):
    def setupUi(self, patientStatus):
        patientStatus.setObjectName("patientStatus")
        patientStatus.resize(1429, 883)
        font = QtGui.QFont()
        font.setFamily("Arial")
        patientStatus.setFont(font)
        self.centralwidget = QtWidgets.QWidget(patientStatus)
        self.centralwidget.setObjectName("centralwidget")

        self.patientListTitle = QtWidgets.QLabel(self.centralwidget)
        self.patientListTitle.setGeometry(QtCore.QRect(620, 30, 231, 51))
        self.patientListTitle.setStyleSheet("font: 25pt \"Arial\";")
        self.patientListTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.patientListTitle.setObjectName("patientListTitle")

        # return to main button
        self.buttBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttBack.setGeometry(QtCore.QRect(30, 30, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttBack.setFont(font)
        self.buttBack.setObjectName("buttBack")

        # confirm button
        self.buttConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.buttConfirm.setGeometry(QtCore.QRect(1252, 30, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.buttConfirm.setFont(font)
        self.buttConfirm.setObjectName("buttConfirm")

        # tab widget
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 110, 1381, 751))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")

        #----------------------- bed tab ------------------------------------------------------------------------
        self.bedTab = QtWidgets.QWidget()
        self.bedTab.setObjectName("bedTab")

        self.bedTable = QtWidgets.QTableWidget(self.bedTab)
        self.bedTable.setGeometry(QtCore.QRect(10, 20, 1131, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.bedTable.setFont(font)
        self.bedTable.setWordWrap(True)
        self.bedTable.setObjectName("bedTable")

        self.bedTable.setColumnCount(12)
        self.bedTable.setRowCount(0)

        # table settings
        self.defColumn(self.bedTable)
        self.bedTable.setColumnWidth(bedColumn,30)
        self.bedTable.setColumnWidth(idColumn,30)
        self.bedTable.setColumnWidth(nameColumn,135)
        self.bedTable.setColumnWidth(detailsColumn,105)
        self.bedTable.setColumnWidth(diagnosisColumn,155)
        self.bedTable.setColumnWidth(isoColumn,75)
        self.bedTable.setColumnWidth(dischargeColumn,75)
        self.bedTable.setColumnWidth(dis_loungeColumn,75)
        self.bedTable.setColumnWidth(dis_sumColumn,75)
        self.bedTable.setColumnWidth(dis_medColumn,75)
        self.bedTable.setColumnWidth(downstreamColumn,125)
        self.bedTable.setColumnWidth(deathColumn,45)

        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.bedTable.setHorizontalHeaderItem(11, item)

        # downstream ward availability on the beds tab
        self.wardFrame = QtWidgets.QFrame(self.bedTab)
        self.wardFrame.setGeometry(QtCore.QRect(1160, 30, 201, 641))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.wardFrame.setFont(font)
        self.wardFrame.setAutoFillBackground(True)
        self.wardFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wardFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wardFrame.setObjectName("wardFrame")

        self.wardBedTitle = QtWidgets.QLabel(self.wardFrame)
        self.wardBedTitle.setGeometry(QtCore.QRect(0, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.wardBedTitle.setFont(font)
        self.wardBedTitle.setStyleSheet("font: 15pt \"Arial\";")
        self.wardBedTitle.setScaledContents(False)
        self.wardBedTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.wardBedTitle.setWordWrap(True)
        self.wardBedTitle.setObjectName("wardBedTitle")

        # cardiology ward (bedTab)
        self.cardioFrame = QtWidgets.QFrame(self.wardFrame)
        self.cardioFrame.setGeometry(QtCore.QRect(20, 90, 161, 91))
        self.cardioFrame.setAutoFillBackground(False)
        self.cardioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardioFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardioFrame.setObjectName("cardioFrame")

        self.cardioTitle = QtWidgets.QLabel(self.cardioFrame)
        self.cardioTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cardioTitle.setFont(font)
        self.cardioTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.cardioTitle.setObjectName("cardioTitle")

        self.cardio = QtWidgets.QLabel(self.cardioFrame)
        self.cardio.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.cardio.setFont(font)
        self.cardio.setText("N/A")
        self.cardio.setAlignment(QtCore.Qt.AlignCenter)
        self.cardio.setObjectName("cardio")

        # endocrinology frame (bedTab)
        self.endoFrame = QtWidgets.QFrame(self.wardFrame)
        self.endoFrame.setGeometry(QtCore.QRect(20, 200, 161, 91))
        self.endoFrame.setAutoFillBackground(False)
        self.endoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endoFrame.setObjectName("endoFrame")

        self.endoTitle = QtWidgets.QLabel(self.endoFrame)
        self.endoTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.endoTitle.setFont(font)
        self.endoTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.endoTitle.setObjectName("endoTitle")

        self.endo = QtWidgets.QLabel(self.endoFrame)
        self.endo.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.endo.setFont(font)
        self.endo.setText("N/A")
        self.endo.setAlignment(QtCore.Qt.AlignCenter)
        self.endo.setObjectName("endo")

        # gastroenterology ward (bedTab)
        self.gastroFrame = QtWidgets.QFrame(self.wardFrame)
        self.gastroFrame.setGeometry(QtCore.QRect(20, 310, 161, 91))
        self.gastroFrame.setAutoFillBackground(False)
        self.gastroFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gastroFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gastroFrame.setObjectName("gastroFrame")

        self.gastroTitle = QtWidgets.QLabel(self.gastroFrame)
        self.gastroTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gastroTitle.setFont(font)
        self.gastroTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.gastroTitle.setObjectName("gastroTitle")

        self.gastro = QtWidgets.QLabel(self.gastroFrame)
        self.gastro.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.gastro.setFont(font)
        self.gastro.setText("N/A")
        self.gastro.setAlignment(QtCore.Qt.AlignCenter)
        self.gastro.setObjectName("gastro")

        # geriatrics ward (bedTab)
        self.geriFrame = QtWidgets.QFrame(self.wardFrame)
        self.geriFrame.setGeometry(QtCore.QRect(20, 420, 161, 91))
        self.geriFrame.setAutoFillBackground(False)
        self.geriFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.geriFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.geriFrame.setObjectName("geriFrame")

        self.geriTitle = QtWidgets.QLabel(self.geriFrame)
        self.geriTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.geriTitle.setFont(font)
        self.geriTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.geriTitle.setObjectName("geriTitle")

        self.geri = QtWidgets.QLabel(self.geriFrame)
        self.geri.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.geri.setFont(font)
        self.geri.setText("N/A")
        self.geri.setAlignment(QtCore.Qt.AlignCenter)
        self.geri.setObjectName("geri")

        # respiratory ward (bedTab)
        self.respFrame = QtWidgets.QFrame(self.wardFrame)
        self.respFrame.setGeometry(QtCore.QRect(20, 530, 161, 91))
        self.respFrame.setAutoFillBackground(False)
        self.respFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.respFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.respFrame.setObjectName("respFrame")

        self.respTitle = QtWidgets.QLabel(self.respFrame)
        self.respTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.respTitle.setFont(font)
        self.respTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.respTitle.setObjectName("respTitle")

        self.resp = QtWidgets.QLabel(self.respFrame)
        self.resp.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.resp.setFont(font)
        self.resp.setText("N/A")
        self.resp.setAlignment(QtCore.Qt.AlignCenter)
        self.resp.setObjectName("resp")

        self.wardFrame.raise_()
        self.bedTable.raise_()
        self.tabWidget.addTab(self.bedTab, "")

        #----------------------- lounge tab --------------------------------------------------------------
        self.loungeTab = QtWidgets.QWidget()
        self.loungeTab.setObjectName("loungeTab")

        self.loungeTable = QtWidgets.QTableWidget(self.loungeTab)
        self.loungeTable.setGeometry(QtCore.QRect(10, 20, 1021, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.loungeTable.setFont(font)
        self.loungeTable.setWordWrap(True)
        self.loungeTable.setObjectName("loungeTable")

        self.loungeTable.setColumnCount(9)
        self.loungeTable.setRowCount(0)

        # table settings
        self.defColumn(self.loungeTable)
        self.loungeTable.setColumnWidth(bedColumn,30)
        self.loungeTable.setColumnWidth(idColumn,30)
        self.loungeTable.setColumnWidth(nameColumn,135)
        self.loungeTable.setColumnWidth(detailsColumn,105)
        self.loungeTable.setColumnWidth(diagnosisColumn,155)
        self.loungeTable.setColumnWidth(isoColumn,75)
        self.loungeTable.setColumnWidth(dischargeColumn,75)
        self.loungeTable.setColumnWidth(dis_loungeColumn,75)
        self.loungeTable.setColumnWidth(dis_sumColumn,75)
        self.loungeTable.setColumnWidth(dis_medColumn,75)

        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.loungeTable.setHorizontalHeaderItem(8, item)

        self.tabWidget.addTab(self.loungeTab, "")


        #----------------------- ward tab -----------------------------------------------------------------
        self.wardTab = QtWidgets.QWidget()
        self.wardTab.setObjectName("wardTab")

        self.wardTable = QtWidgets.QTableWidget(self.wardTab)
        self.wardTable.setGeometry(QtCore.QRect(10, 20, 1131, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.wardTable.setFont(font)
        self.wardTable.setWordWrap(True)
        self.wardTable.setObjectName("wardTable")

        self.wardTable.setColumnCount(8)
        self.wardTable.setRowCount(0)

        # table settings
        self.defColumn(self.wardTable)
        self.wardTable.setColumnWidth(bedColumn,30)
        self.wardTable.setColumnWidth(idColumn,30)
        self.wardTable.setColumnWidth(nameColumn,135)
        self.wardTable.setColumnWidth(detailsColumn,105)
        self.wardTable.setColumnWidth(diagnosisColumn,155)
        self.wardTable.setColumnWidth(isoColumn,75)
        self.wardTable.setColumnWidth(downstreamColumn,125)
        self.wardTable.setColumnWidth(sentColumn,75)

        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.wardTable.setHorizontalHeaderItem(7, item)

        # downstream ward bed availability for ward tab
        self.wardFrame_2 = QtWidgets.QFrame(self.wardTab)
        self.wardFrame_2.setGeometry(QtCore.QRect(1160, 30, 201, 641))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.wardFrame_2.setFont(font)
        self.wardFrame_2.setAutoFillBackground(True)
        self.wardFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wardFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wardFrame_2.setObjectName("wardFrame_2")

        self.wardBedTitle_2 = QtWidgets.QLabel(self.wardFrame_2)
        self.wardBedTitle_2.setGeometry(QtCore.QRect(0, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.wardBedTitle_2.setFont(font)
        self.wardBedTitle_2.setStyleSheet("font: 15pt \"Arial\";")
        self.wardBedTitle_2.setScaledContents(False)
        self.wardBedTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.wardBedTitle_2.setWordWrap(True)
        self.wardBedTitle_2.setObjectName("wardBedTitle_2")

        # cardiology ward (wardTab)
        self.cardioFrame_2 = QtWidgets.QFrame(self.wardFrame_2)
        self.cardioFrame_2.setGeometry(QtCore.QRect(20, 90, 161, 91))
        self.cardioFrame_2.setAutoFillBackground(False)
        self.cardioFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardioFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardioFrame_2.setObjectName("cardioFrame_2")

        self.cardioTitle_2 = QtWidgets.QLabel(self.cardioFrame_2)
        self.cardioTitle_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cardioTitle_2.setFont(font)
        self.cardioTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cardioTitle_2.setObjectName("cardioTitle_2")

        self.cardio_2 = QtWidgets.QLabel(self.cardioFrame_2)
        self.cardio_2.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.cardio_2.setFont(font)
        self.cardio_2.setText("N/A")
        self.cardio_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cardio_2.setObjectName("cardio_2")

        # endocrinology ward (wardTab)
        self.endoFrame_2 = QtWidgets.QFrame(self.wardFrame_2)
        self.endoFrame_2.setGeometry(QtCore.QRect(20, 200, 161, 91))
        self.endoFrame_2.setAutoFillBackground(False)
        self.endoFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endoFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endoFrame_2.setObjectName("endoFrame_2")

        self.endoTitle_2 = QtWidgets.QLabel(self.endoFrame_2)
        self.endoTitle_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.endoTitle_2.setFont(font)
        self.endoTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.endoTitle_2.setObjectName("endoTitle_2")

        self.endo_2 = QtWidgets.QLabel(self.endoFrame_2)
        self.endo_2.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.endo_2.setFont(font)
        self.endo_2.setText("N/A")
        self.endo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.endo_2.setObjectName("endo_2")

        # gastroenterology ward (wardTab)
        self.gastroFrame_2 = QtWidgets.QFrame(self.wardFrame_2)
        self.gastroFrame_2.setGeometry(QtCore.QRect(20, 310, 161, 91))
        self.gastroFrame_2.setAutoFillBackground(False)
        self.gastroFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gastroFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gastroFrame_2.setObjectName("gastroFrame_2")

        self.gastroTitle_2 = QtWidgets.QLabel(self.gastroFrame_2)
        self.gastroTitle_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gastroTitle_2.setFont(font)
        self.gastroTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gastroTitle_2.setObjectName("gastroTitle_2")

        self.gastro_2 = QtWidgets.QLabel(self.gastroFrame_2)
        self.gastro_2.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.gastro_2.setText("N/A")
        self.gastro_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gastro_2.setObjectName("gastro_2")

        # geriatrics ward (wardTab)
        self.geriFrame_2 = QtWidgets.QFrame(self.wardFrame_2)
        self.geriFrame_2.setGeometry(QtCore.QRect(20, 420, 161, 91))
        self.geriFrame_2.setAutoFillBackground(False)
        self.geriFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.geriFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.geriFrame_2.setObjectName("geriFrame_2")

        self.geriTitle_2 = QtWidgets.QLabel(self.geriFrame_2)
        self.geriTitle_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.geriTitle_2.setFont(font)
        self.geriTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.geriTitle_2.setObjectName("geriTitle_2")

        self.geri_2 = QtWidgets.QLabel(self.geriFrame_2)
        self.geri_2.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.geri_2.setFont(font)
        self.geri_2.setText("N/A")
        self.geri_2.setAlignment(QtCore.Qt.AlignCenter)
        self.geri_2.setObjectName("geri_2")

        # respiratory ward (wardTab)
        self.respFrame_2 = QtWidgets.QFrame(self.wardFrame_2)
        self.respFrame_2.setGeometry(QtCore.QRect(20, 530, 161, 91))
        self.respFrame_2.setAutoFillBackground(False)
        self.respFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.respFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.respFrame_2.setObjectName("respFrame_2")

        self.respTitle_2 = QtWidgets.QLabel(self.respFrame_2)
        self.respTitle_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.respTitle_2.setFont(font)
        self.respTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.respTitle_2.setObjectName("respTitle_2")

        self.resp_2 = QtWidgets.QLabel(self.respFrame_2)
        self.resp_2.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.resp_2.setFont(font)
        self.resp_2.setText("N/A")
        self.resp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resp_2.setObjectName("resp_2")

        self.tabWidget.addTab(self.wardTab, "")

        self.tabWidget.raise_()
        self.patientListTitle.raise_()
        self.buttBack.raise_()
        self.buttConfirm.raise_()

        patientStatus.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(patientStatus)
        self.statusbar.setObjectName("statusbar")
        patientStatus.setStatusBar(self.statusbar)

        self.retranslateUi(patientStatus)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(patientStatus)


        # BUTTON/CHECKBOX CONNECTIONS
        self.buttConfirm.clicked.connect(self.confirmChanges)
        

        # display patient info in tables on bed, lounge & downstream tabs
        self.displayList(self.bedTable)
        self.displayList(self.loungeTable)
        self.displayList(self.wardTable)
        self.displayWardBeds()


    def displayList(self, table):      # this function updates the list of patients currently in an AMU bed that is saved in database

        if table == self.bedTable:
            size = getBedListSize()
            listnow = getPatientsinBed()
        elif table == self.loungeTable:
            size = getLoungeListSize()
            listnow = getPatientsinLounge()
        elif table == self.wardTable:
            size = getDownstreamListSize()
            listnow = getPatientsDownstream()

        print(listnow)
        print("^^^^^this is patients in "+table.objectName())


        self.defColumn(table)

        table.setRowCount(size) #setting the table row size
        row = 0
       
        for pat in listnow: #looping through each row of bed list to display each line/patient
            
            patient = getPatientInfo(pat[0])

            isoStatus = ""
            if patient[6] == 0:
                isoStatus = "N"
            elif patient[6] != 0:
                isoStatus = "Y"
                
            # creating widgets for the table cells
            checkBox_discharge = QtWidgets.QTableWidgetItem()
            checkBox_discharge.setCheckState(pat[2])

            checkBox_dischargeLounge = QtWidgets.QTableWidgetItem()
            checkBox_dischargeLounge.setCheckState(pat[3])

            checkBox_dischargeSum = QtWidgets.QTableWidgetItem()
            checkBox_dischargeSum.setCheckState(pat[4])

            checkBox_dischargeMed = QtWidgets.QTableWidgetItem()
            checkBox_dischargeMed.setCheckState(pat[5])

            comboBox_ward = QtWidgets.QComboBox()
            comboBox_ward.addItem("Select")
            comboBox_ward.addItem("Cardiology")
            comboBox_ward.addItem("Endocrinology")
            comboBox_ward.addItem("Gastroenterology")
            comboBox_ward.addItem("Geriatrics")
            comboBox_ward.addItem("Respiratory")
            comboBox_ward.setCurrentText(pat[6])

            checkBox_death = QtWidgets.QTableWidgetItem()
            checkBox_death.setCheckState(pat[7])

            checkBox_sent = QtWidgets.QTableWidgetItem()
            checkBox_sent.setCheckState(0)

            table.setRowHeight(row, 70)
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)

            item.setText(str(patient[0]))
            table.setItem(row, idColumn, item) #id
            table.setItem(row, nameColumn, QtWidgets.QTableWidgetItem("{} {}".format(patient[1], patient[2]))) # name
            table.setItem(row, detailsColumn, QtWidgets.QTableWidgetItem(("Age: {} \nGender: {}").format(patient[3],patient[4]))) #age and gender
            table.setItem(row, diagnosisColumn, QtWidgets.QTableWidgetItem(("{}").format(patient[5]))) # diagnosis
            table.setItem(row, isoColumn, QtWidgets.QTableWidgetItem(isoStatus)) # isolation

            if table == self.bedTable:
                table.setItem(row, bedColumn, QtWidgets.QTableWidgetItem(pat[1])) # bed
                table.setItem(row, dischargeColumn, checkBox_discharge) # discharge status
                table.setItem(row, dis_loungeColumn, checkBox_dischargeLounge) # discharge lounge
                table.setItem(row, dis_sumColumn, checkBox_dischargeSum) # discharge summary
                table.setItem(row, dis_medColumn, checkBox_dischargeMed) # discharge medication
                table.setCellWidget(row, downstreamColumn, comboBox_ward) # downstream ward
                table.setItem(row, deathColumn, checkBox_death) # death


            elif table == self.loungeTable:
                table.setItem(row, dischargeColumn, checkBox_discharge) # discharge status
                table.setItem(row, dis_loungeColumn, checkBox_dischargeLounge) # discharge lounge
                table.setItem(row, dis_sumColumn, checkBox_dischargeSum) # discharge summary
                table.setItem(row, dis_medColumn, checkBox_dischargeMed) # discharge medication

            elif table == self.wardTable:
                table.setItem(row, bedColumn, QtWidgets.QTableWidgetItem(pat[1])) # bed
                table.setItem(row, downstreamColumn, QtWidgets.QTableWidgetItem(pat[6])) # downstream ward (display only, edit in beds tab)
                table.setItem(row, sentColumn, checkBox_sent) # sent (to downstream)

            row = row+1



#-------------------- functions to CONFIRM changes ------------------------------

    def confirmChanges(self):
        self.confirmBed()
        self.confirmLounge()
        self.confirmWard()

        self.finalDischarge()

        self.displayList(self.bedTable)
        self.displayList(self.loungeTable)
        self.displayList(self.wardTable)
        self.displayWardBeds()

    # confirm changes made on bed table

    def confirmBed(self):
        table = self.bedTable
        rowNum = table.rowCount()
        self.defColumn(table)
        for row in range(rowNum):
            # fetch patID
            patID = table.item(row,idColumn).text()
            print("patID:"+patID)

            # fetch discharge, downstream, death
            checkBox_discharge = table.item(row,dischargeColumn)
            comboBox_ward = table.cellWidget(row,downstreamColumn)
            checkBox_death = table.item(row,deathColumn)

            n_dis = checkBox_discharge.checkState()
            n_ward = comboBox_ward.currentText()
            n_death = checkBox_death.checkState()

            if n_dis > 0 and n_ward == "Select" and n_death == 0:
                dis_lounge = table.item(row,dis_loungeColumn)
                dis_sum = table.item(row,dis_sumColumn)
                dis_med = table.item(row,dis_medColumn)

                n_disL = dis_lounge.checkState()
                n_disS = dis_sum.checkState()
                n_disM = dis_med.checkState()

                # update database
                updateCheck_discharge(patID, n_dis)
                updateCheck_dischargeLounge(patID, dis_lounge.checkState())
                updateCheck_dischargeSum(patID, dis_sum.checkState())
                updateCheck_dischargeMed(patID, dis_med.checkState())

            elif n_ward != "Select" and n_dis == 0 and n_death == 0:
                updateWard(patID, n_ward)
            
            elif n_death > 0:
                deletePatfromBed(patID)
                print("deleted patient form death:"+patID)

            else:
                pass



    # confirm changes made on lounge table

    def confirmLounge(self):
        table = self.loungeTable
        rowNum = table.rowCount()
        self.defColumn(table)
        for row in range(rowNum):
            
            patID = table.item(row,idColumn).text()     # fetch patID

            checkBox_discharge = table.item(row,dischargeColumn)    # fetch discharge checkbox
            n_dis = checkBox_discharge.checkState()

            if n_dis > 0:   # ensure discharge instruction is still in place
                dis_lounge = table.item(row,dis_loungeColumn)
                dis_sum = table.item(row,dis_sumColumn)
                dis_med = table.item(row,dis_medColumn)

                # update database
                updateCheck_discharge(patID, n_dis)     
                updateCheck_dischargeLounge(patID, dis_lounge.checkState())
                updateCheck_dischargeSum(patID, dis_sum.checkState())
                updateCheck_dischargeMed(patID, dis_med.checkState())



    # confirm changes made on ward table

    def confirmWard(self):
        table = self.wardTable
        rowNum = table.rowCount()
        self.defColumn(table)

        for row in range(rowNum):
            patID = table.item(row,idColumn).text()
            checkBox_sent = table.item(row,sentColumn)
            n_sent = checkBox_sent.checkState()

            if n_sent > 0:
                deletePatfromBed(patID)
                print("deleted patient from downstream:"+patID)



    # function to delete patients from database if they are discharged, and summary & meds have been done

    def finalDischarge(self):
        dischargePats = getPatientsDischarged()     # fetch list of patients that have met requirement to be discharged
        print(dischargePats)
        print("^^^^^^^^^^^^^^^ discharged pats ^^^^^^^^^^^^^^^^^")
        for pat in dischargePats:
            deletePatfromBed(pat[0])    # delete patient from database
            print("deleted patient for discharge:")




##----------------- defining columns with variables based on the table in question ------------------------##

    def defColumn(self, table):
        global bedColumn, idColumn, nameColumn, detailsColumn, diagnosisColumn, isoColumn, dischargeColumn, dis_loungeColumn, dis_sumColumn, dis_medColumn, downstreamColumn, deathColumn, sentColumn
        if table == self.bedTable:
            bedColumn = 0
            idColumn = 1
            nameColumn = 2
            detailsColumn = 3
            diagnosisColumn = 4
            isoColumn = 5
            dischargeColumn = 6
            dis_loungeColumn = 7
            dis_sumColumn = 8
            dis_medColumn = 9
            downstreamColumn = 10
            deathColumn = 11
        elif table == self.loungeTable:
            idColumn = 0
            nameColumn = 1
            detailsColumn = 2
            diagnosisColumn = 3
            isoColumn = 4
            dischargeColumn = 5
            dis_loungeColumn = 6
            dis_sumColumn = 7
            dis_medColumn = 8
        elif table == self.wardTable:
            bedColumn = 0
            idColumn = 1
            nameColumn = 2
            detailsColumn = 3
            diagnosisColumn = 4
            isoColumn = 5
            downstreamColumn = 6
            sentColumn = 7



##---------------------- function to display wardAvailability --------------------##

    def displayWardBeds(self):

        wards = getWardAvailability() # get the number of free beds in the database as a list

        # set ward free beds as zero if database has no info
        if wards == []:
            wardBeds = [0,0,0,0,0]
        else:
            wardBeds = wards[0]

        self.cardio.setText(str(wardBeds[0]))
        self.endo.setText(str(wardBeds[1]))
        self.gastro.setText(str(wardBeds[2]))
        self.geri.setText(str(wardBeds[3]))
        self.resp.setText(str(wardBeds[4]))
        self.cardio_2.setText(str(wardBeds[0]))
        self.endo_2.setText(str(wardBeds[1]))
        self.gastro_2.setText(str(wardBeds[2]))
        self.geri_2.setText(str(wardBeds[3]))
        self.resp_2.setText(str(wardBeds[4]))





    def retranslateUi(self, patientStatus):
        _translate = QtCore.QCoreApplication.translate
        patientStatus.setWindowTitle(_translate("patientStatus", "Waiting List"))
        self.patientListTitle.setText(_translate("patientStatus", "Patient Status"))
        self.buttBack.setText(_translate("patientStatus", "Return to Main"))
        self.buttConfirm.setText(_translate("patientStatus", "Confirm"))
        item = self.bedTable.horizontalHeaderItem(0)
        item.setText(_translate("patientStatus", "Bed"))
        item = self.bedTable.horizontalHeaderItem(1)
        item.setText(_translate("patientStatus", "ID"))
        item = self.bedTable.horizontalHeaderItem(2)
        item.setText(_translate("patientStatus", "Name"))
        item = self.bedTable.horizontalHeaderItem(3)
        item.setText(_translate("patientStatus", "Details"))
        item = self.bedTable.horizontalHeaderItem(4)
        item.setText(_translate("patientStatus", "Diagnosis"))
        item = self.bedTable.horizontalHeaderItem(5)
        item.setText(_translate("patientStatus", "Isolation"))
        item = self.bedTable.horizontalHeaderItem(6)
        item.setText(_translate("patientStatus", "Discharge"))
        item = self.bedTable.horizontalHeaderItem(7)
        item.setText(_translate("patientStatus", "Lounge"))
        item = self.bedTable.horizontalHeaderItem(8)
        item.setText(_translate("patientStatus", "Summary"))
        item = self.bedTable.horizontalHeaderItem(9)
        item.setText(_translate("patientStatus", "Medication"))
        item = self.bedTable.horizontalHeaderItem(10)
        item.setText(_translate("patientStatus", "Downstream"))
        item = self.bedTable.horizontalHeaderItem(11)
        item.setText(_translate("patientStatus", "Death"))
        self.wardBedTitle.setText(_translate("patientStatus", "Downstream Ward Bed Availabity"))
        self.cardioTitle.setText(_translate("patientStatus", "Cardiology"))
        self.endoTitle.setText(_translate("patientStatus", "Endocrinology"))
        self.gastroTitle.setText(_translate("patientStatus", "Gastroenterology"))
        self.geriTitle.setText(_translate("patientStatus", "Geriatrics"))
        self.respTitle.setText(_translate("patientStatus", "Respiratory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bedTab), _translate("patientStatus", "Beds"))
        item = self.loungeTable.horizontalHeaderItem(0)
        item.setText(_translate("patientStatus", "ID"))
        item = self.loungeTable.horizontalHeaderItem(1)
        item.setText(_translate("patientStatus", "Name"))
        item = self.loungeTable.horizontalHeaderItem(2)
        item.setText(_translate("patientStatus", "Details"))
        item = self.loungeTable.horizontalHeaderItem(3)
        item.setText(_translate("patientStatus", "Diagnosis"))
        item = self.loungeTable.horizontalHeaderItem(4)
        item.setText(_translate("patientStatus", "Isolation"))
        item = self.loungeTable.horizontalHeaderItem(5)
        item.setText(_translate("patientStatus", "Discharge"))
        item = self.loungeTable.horizontalHeaderItem(6)
        item.setText(_translate("patientStatus", "Lounge"))
        item = self.loungeTable.horizontalHeaderItem(7)
        item.setText(_translate("patientStatus", "Summary"))
        item = self.loungeTable.horizontalHeaderItem(8)
        item.setText(_translate("patientStatus", "Medication"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loungeTab), _translate("patientStatus", "Discharge Lounge"))
        item = self.wardTable.horizontalHeaderItem(0)
        item.setText(_translate("patientStatus", "Bed"))
        item = self.wardTable.horizontalHeaderItem(1)
        item.setText(_translate("patientStatus", "ID"))
        item = self.wardTable.horizontalHeaderItem(2)
        item.setText(_translate("patientStatus", "Name"))
        item = self.wardTable.horizontalHeaderItem(3)
        item.setText(_translate("patientStatus", "Details"))
        item = self.wardTable.horizontalHeaderItem(4)
        item.setText(_translate("patientStatus", "Diagnosis"))
        item = self.wardTable.horizontalHeaderItem(5)
        item.setText(_translate("patientStatus", "Isolation"))
        item = self.wardTable.horizontalHeaderItem(6)
        item.setText(_translate("patientStatus", "Downstream"))
        item = self.wardTable.horizontalHeaderItem(7)
        item.setText(_translate("patientStatus", "Sent"))
        self.wardBedTitle_2.setText(_translate("patientStatus", "Downstream Ward Bed Availabity"))
        self.cardioTitle_2.setText(_translate("patientStatus", "Cardiology"))
        self.endoTitle_2.setText(_translate("patientStatus", "Endocrinology"))
        self.gastroTitle_2.setText(_translate("patientStatus", "Gastroenterology"))
        self.geriTitle_2.setText(_translate("patientStatus", "Geriatrics"))
        self.respTitle_2.setText(_translate("patientStatus", "Respiratory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wardTab), _translate("patientStatus", "Downstream"))

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    patientStatus = QtWidgets.QMainWindow()
    ui = Ui_patientStatus()
    ui.setupUi(patientStatus)
    patientStatus.show()
    sys.exit(app.exec_())