# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from waitlist import Ui_waitlist

class Ui_registerform(object):
    def addedPatient(self, reg_win, wait_win):
        wait_win.show()
        reg_win.hide()

    def setupUi(self, registerform, waitlist):
        registerform.setObjectName("registerform")
        registerform.resize(588, 421)
        self.lineEdit = QtWidgets.QLineEdit(registerform)
        self.lineEdit.setGeometry(QtCore.QRect(90, 30, 341, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(registerform)
        self.textEdit.setGeometry(QtCore.QRect(30, 170, 531, 191))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(registerform)
        self.label.setGeometry(QtCore.QRect(30, 30, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(registerform)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.ageBox = QtWidgets.QSpinBox(registerform)
        self.ageBox.setGeometry(QtCore.QRect(90, 70, 31, 24))
        self.ageBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ageBox.setWrapping(True)
        self.ageBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ageBox.setSuffix("")
        self.ageBox.setMaximum(150)
        self.ageBox.setObjectName("ageBox")
        self.label_3 = QtWidgets.QLabel(registerform)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.genderBox = QtWidgets.QComboBox(registerform)
        self.genderBox.setGeometry(QtCore.QRect(90, 110, 105, 28))
        self.genderBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.genderBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.genderBox.setEditable(False)
        self.genderBox.setCurrentText("")
        self.genderBox.setMaxVisibleItems(2)
        self.genderBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.genderBox.setObjectName("genderBox")
        self.label_4 = QtWidgets.QLabel(registerform)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 121, 16))
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(registerform,clicked = lambda: self.addedPatient(registerform, waitlist))
        self.pushButton.setGeometry(QtCore.QRect(240, 370, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.genderBox.addItem("Select")
        self.genderBox.addItem("Male")
        self.genderBox.addItem("Female")
        

        self.retranslateUi(registerform)
        QtCore.QMetaObject.connectSlotsByName(registerform)

    def retranslateUi(self, registerform):
        _translate = QtCore.QCoreApplication.translate
        registerform.setWindowTitle(_translate("registerform", "Patient Registration Form"))
        self.label.setText(_translate("registerform", "Name:"))
        self.label_2.setText(_translate("registerform", "Age:"))
        self.label_3.setText(_translate("registerform", "Gender:"))
        self.label_4.setText(_translate("registerform", "Top-line Diagnosis"))
        self.pushButton.setText(_translate("registerform", "Add Patient"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerform = QtWidgets.QGroupBox()
    ui = Ui_registerform()
    ui.setupUi(registerform)
    registerform.show()
    sys.exit(app.exec_())
