# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wardBedEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from amu_database import getWardAvailability, updateWardBeds, deleteWardBeds

cardioRow = 0
endoRow = 1
gastroRow = 2
geriRow = 3
respRow = 4
freeColumn = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wardBedEdit = QtWidgets.QTableWidget(self.centralwidget)
        self.wardBedEdit.setGeometry(QtCore.QRect(120, 100, 391, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.wardBedEdit.setFont(font)
        self.wardBedEdit.setObjectName("wardBedEdit")
        self.wardBedEdit.setColumnCount(1)
        self.wardBedEdit.setRowCount(5)

        # table settings
        self.wardBedEdit.setRowHeight(cardioRow, 55)
        self.wardBedEdit.setRowHeight(endoRow, 55)
        self.wardBedEdit.setRowHeight(gastroRow, 55)
        self.wardBedEdit.setRowHeight(geriRow, 55)
        self.wardBedEdit.setRowHeight(respRow, 55)
        self.wardBedEdit.setColumnWidth(freeColumn,200)

        # display table values
        self.displayList()

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wardBedEdit.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wardBedEdit.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wardBedEdit.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wardBedEdit.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wardBedEdit.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.wardBedEdit.setHorizontalHeaderItem(0, item)

        # confirm changes button
        self.buttConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.buttConfirm.setGeometry(QtCore.QRect(480, 20, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.buttConfirm.setFont(font)
        self.buttConfirm.setObjectName("buttConfirm")

        # page title
        self.wardAvailTitle = QtWidgets.QLabel(self.centralwidget)
        self.wardAvailTitle.setGeometry(QtCore.QRect(200, 20, 251, 51))
        self.wardAvailTitle.setStyleSheet("font: 25pt \"Arial\";")
        self.wardAvailTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.wardAvailTitle.setObjectName("wardAvailTitle")

        # back button to return to main
        self.buttBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttBack.setGeometry(QtCore.QRect(20, 20, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttBack.setFont(font)
        self.buttBack.setObjectName("buttBack")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)\

        # button connections
        #self.buttBack.clicked.connect()
        self.buttConfirm.clicked.connect(self.confirmWardBeds)


    def displayList(self):
        
        wards = getWardAvailability() # get the number of free beds in the database as a list

        # set ward free beds as zero if database has no info
        if wards == []:
            wardBeds = [0,0,0,0,0]
        else:
            wardBeds = wards[0]

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)

        self.wardBedEdit.setItem(cardioRow, freeColumn, QtWidgets.QTableWidgetItem("{}".format(wardBeds[0]))) #cardio
        self.wardBedEdit.setItem(endoRow, freeColumn, QtWidgets.QTableWidgetItem("{}".format(wardBeds[1]))) #endocrinology
        self.wardBedEdit.setItem(gastroRow, freeColumn, QtWidgets.QTableWidgetItem("{}".format(wardBeds[2]))) #gastroenterology
        self.wardBedEdit.setItem(geriRow, freeColumn, QtWidgets.QTableWidgetItem("{}".format(wardBeds[3]))) #geriatrics
        self.wardBedEdit.setItem(respRow, freeColumn, QtWidgets.QTableWidgetItem("{}".format(wardBeds[4]))) #respiratory


    def confirmWardBeds(self):
        
        deleteWardBeds()        # wipe bed availability database
        
        wardUpdate = []
        for ward in range(5):
            item = self.wardBedEdit.item(ward, freeColumn)          # item(row, 0) Returns the item for the given row and column if one has been set; otherwise returns nullptr.
            if item:
                item = self.wardBedEdit.item(ward, freeColumn).text()
                wardUpdate.append(item)

        updateWardBeds(wardUpdate[0], wardUpdate[1], wardUpdate[2], wardUpdate[3], wardUpdate[4])
        self.displayList()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.wardBedEdit.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cardiology"))
        item = self.wardBedEdit.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Endocrinology"))
        item = self.wardBedEdit.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gastroenterology"))
        item = self.wardBedEdit.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Geriatrics"))
        item = self.wardBedEdit.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Respiratory"))
        item = self.wardBedEdit.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Available Beds"))
        self.buttConfirm.setText(_translate("MainWindow", "Confirm"))
        self.wardAvailTitle.setText(_translate("MainWindow", "Ward Availability"))
        self.buttBack.setText(_translate("MainWindow", "Return to Main"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
